name: Build Docker Image

on:
  push:
    braches:  [ main ]
  pull_request:
    braches:  [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run:  |
          docker build -t fashion-mnist-classifier-cpu:latest -f docker/Dockerfile.cpu .

      - name: Run training inside Docker
        run:  |
          docker run --rm fashion-mnist-classifier-cpu:latest python3 scripts/train.py

      - name: Test the image by running a script
        # Verify image build 
        run:  |
          docker run --rm fashion-mnist-classifier-cpu:latest python3 scripts/train.py --epochs 2