name: Deploy Docs to GitHub Pages

on: 
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
  # Allows workflow to be run manually from the Actions tab
  workflow_dispatch:

# Grant GITHUB_TOKEN permissions for deployment
permissions:
  contents: read
  pages:  write
  id-token: write

jobs:
  # Build Job
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkou Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install Documentation Dependencies
        run:  |
          python3 -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings mkdocstrings-python
          pip install -e .
        
      - name: Build MKDocs Documentation
        run:  mkdocs build --clean --strict
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  # Deployment     
  deploy:
    environment:
      name: github-pages
      url:  ${{steps.deployment.outputs.page_url}}
    runs-on:  ubuntu-latest
    needs:  build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3